alias update='sudo apt-get update -y && sudo apt-get upgrade -y'
alias checkip='curl checkip.amazonaws.com'
alias checkip6='curl -6 icanhazip.com'
alias ..='cd ..'

#jump to containerd directory
alias ctrd='cd "${GOPATH}"/src/github.com/containerd'

#jump to kubernetes directory
alias kdir='cd "${GOPATH}"/src/github.com/kubernetes'

#jump to opencontainers directory
alias ocid='cd "${GOPATH}"/src/github.com/opencontainers'

#exclude grepping through .git folders and make case insensitive
alias grep='grep -i --exclude-dir=\.git --color=auto'
#grep with context
alias grepc='grep -C 5'

#generate output in human readable form
alias du='du -h'
alias df='df -h'
alias free='free -h'

# alias sudo with path so that $PATH is always available
alias mysudo='sudo -E env "PATH=$PATH"'

# kubectl alias
alias k='kubectl'
alias kn='kubectl -n "$KUBERNETES_NS"'

# cat alias
alias cat='batcat'

# use lima + nerdctl
alias dockerl='lima nerdctl'

# git aliases
alias ga='git add'
__git_complete ga _git_add
alias gb='git branch'
__git_complete gb _git_branch
alias gbd='git branch -D'
__git_complete gbd _git_branch
alias gc='git ci'
__git_complete gc _git_commit
alias gcb='git checkout -b'
__git_complete gcb _git_checkout
alias gco='git checkout'
__git_complete gco _git_checkout
alias gd='git diff'
__git_complete gd _git_diff
alias gf='git fetch'
__git_complete gf _git_fetch
alias gl='git log --stat'
__git_complete gl _git_log
alias gp='git push'
__git_complete gp _git_push
alias gst='git status --short'
__git_complete gst _git_status

# function to list most recently active 10 branches
gbs() {
	git for-each-ref --sort=-committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:green)%(committerdate:relative)%(color:reset) - %(contents:subject)' | head -n 10
}

#use GUI diff tool which comes along with goland
gdiff() {
	goland diff $1 $2
}

#make directory and go into it
mkcd() { 
	mkdir -p $1; cd $1 
}

#make temp directory and cd into it
mktcd() {
        name=$(mktemp -d); cd $name
}

#search through history
hs() { 
	command="history"
	for arg in "$@"
	do
		command="$command | grep $arg"
	done
	eval $command
}

#mv with parent
pmv() {
    src=$1
    dst=$2
    mkdir -p "$dst"/"$(dirname $src)"
    mv "$src" "$dst"/"$(dirname $src)"/
}

#Extract archives
extract() {
	if [ -f $1 ] ; then
		case $1 in
		  *.tar.bz2)   tar xjvf $1    ;;
		  *.tar.gz)    tar xzvf $1    ;;
		  *.bz2)       bzip2 -d $1    ;;
		  *.rar)       unrar $1    ;;
		  *.gz)        gunzip $1    ;;
		  *.tar)       tar xf $1    ;;
		  *.tgz)       tar xzf $1    ;;
		  *.zip)       unzip $1     ;;
		  *.7z)        7z x $1    ;;
		  *)           echo "'$1' cannot be extracted via extract()"   ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}

#cd multiple dricetories
up() {
	DIR_PATH=""

	if [ -z $1 ] ; then
		return
	fi

	for i in $(seq "$1")
	do
		DIR_PATH="$DIR_PATH../"
	done
	cd $DIR_PATH
}

gi() { 
	curl -sL https://www.gitignore.io/api/$@
	echo ""
}

